module.exports = {
  apps: [
    {
      name: 'jasabersih-api',
      cwd: '/var/www/jasabersih/apps/api',
      script: '/bin/bash',
      args: "-lc 'cd /var/www/jasabersih/apps/api && exec node --no-warnings --dns-result-order=ipv4first -r ts-node/register src/main.ts'",
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: '5000',
        R2_SKIP_CORS_INIT: 'true',
      },
      max_memory_restart: '512M',
      error_file: '/var/log/pm2/jasabersih-api.err.log',
      out_file: '/var/log/pm2/jasabersih-api.out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'jasabersih-admin',
      cwd: '/var/www/jasabersih/apps/admin',
      script: 'pnpm',
      args: 'exec next start -p 3001',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production' },
      max_memory_restart: '512M',
      error_file: '/var/log/pm2/jasabersih-admin.err.log',
      out_file: '/var/log/pm2/jasabersih-admin.out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
